"use client";
import { Bell, CheckCheck, RefreshCw } from "lucide-react";
import { useState } from "react";
import { useAnnouncements } from "@/components/announcement-provider";
import { LiveAnnouncementCard } from "@/components/live-announcement-card";
import { EmptyState,PageHeader } from "@/components/ui";
import { AnnouncementCategory } from "@/lib/announcement-types";
const filters:("All"|AnnouncementCategory)[]=["All","General","Schedule Update","Urgent","Reminder","Opportunity"];
export default function Announcements(){const {announcements,loading,error,refresh,markAllRead,unreadCount}=useAnnouncements();const [filter,setFilter]=useState<(typeof filters)[number]>("All");const shown=filter==="All"?announcements:announcements.filter(a=>a.category===filter);return <div className="mx-auto max-w-3xl"><PageHeader eyebrow={`${unreadCount} unread`} title="Announcements"/><div className="mb-4 flex items-center justify-between gap-3"><button onClick={refresh} className="flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-xs font-bold"><RefreshCw size={14}/>Refresh</button>{unreadCount>0&&<button onClick={markAllRead} className="flex items-center gap-2 text-xs font-extrabold text-[var(--dark-cyan)]"><CheckCheck size={15}/>Mark all as read</button>}</div><div className="no-scrollbar -mx-4 mb-5 flex gap-2 overflow-x-auto px-4 pb-1">{filters.map(item=><button key={item} onClick={event=>{setFilter(item);event.currentTarget.parentElement?.scrollTo({left:event.currentTarget.offsetLeft-16,behavior:"smooth"})}} className={`shrink-0 rounded-full border px-3.5 py-2 text-xs font-extrabold ${filter===item?"border-[var(--dark-cyan)] bg-[var(--dark-cyan)] text-white":"border-[var(--line)] bg-white"}`}>{item}</button>)}</div>{loading?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="card h-32 animate-pulse bg-white/60"/>)}</div>:error?<div className="card p-6 text-center"><p className="font-bold text-[#9a4d4d]">Couldn’t load announcements</p><p className="mt-1 text-sm text-[var(--muted)]">{error}</p><button onClick={refresh} className="mt-3 font-bold text-[var(--dark-cyan)]">Try again</button></div>:shown.length?<div className="space-y-3">{shown.map(item=><LiveAnnouncementCard key={item.id} item={item}/>)}</div>:<EmptyState title="Nothing here yet" body={filter==="All"?"New conference updates will appear here.":`No ${filter.toLowerCase()} announcements.`}/>}<p className="mt-8 flex items-center justify-center gap-2 text-center text-xs text-[var(--muted)]"><Bell size={13}/>Live updates appear automatically while the app is open.</p></div>}
