"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { FormEvent, useCallback, useEffect, useState } from "react";
import { LogOut, Pencil, Pin, PinOff, Trash2, X } from "lucide-react";
import type { Announcement, AnnouncementCategory } from "@/lib/announcement-types";

const categories: { value: AnnouncementCategory; label: string }[] = [
  { value: "general", label: "General" }, { value: "urgent", label: "Urgent" }, { value: "link", label: "Link" },
];

export function AdminDashboard({token,onLogout}:{token:string;onLogout:()=>void}){
  const [items,setItems]=useState<Announcement[]>([]);const [editingId,setEditingId]=useState<string|null>(null);const [title,setTitle]=useState("");const [message,setMessage]=useState("");const [linkUrl,setLinkUrl]=useState("");const [category,setCategory]=useState<AnnouncementCategory>("general");const [pinned,setPinned]=useState(false);const [sendNotification,setSendNotification]=useState(false);const [notificationSender,setNotificationSender]=useState("");const [error,setError]=useState("");const [notice,setNotice]=useState("");const [saving,setSaving]=useState(false);const authHeaders={Authorization:`Bearer ${token}`};
  const load=useCallback(async()=>{const response=await fetch("/api/admin/announcements",{cache:"no-store",headers:{Authorization:`Bearer ${token}`}});const result=await response.json();if(!response.ok)throw new Error(result.error);setItems(result)},[token]);
  useEffect(()=>{load().catch(issue=>setError(issue.message))},[load]);
  function reset(){setEditingId(null);setTitle("");setMessage("");setLinkUrl("");setCategory("general");setPinned(false);setSendNotification(false);setNotificationSender("");setError("")}
  function edit(item:Announcement){setEditingId(item.id);setTitle(item.title);setMessage(item.message||"");setLinkUrl(item.link_url||"");setNotificationSender(item.sender||"YLC");setCategory(item.category);setPinned(item.is_pinned);setSendNotification(false);setError("");setNotice("");window.scrollTo({top:0,behavior:"smooth"})}
  function changeCategory(next:AnnouncementCategory){setCategory(next);if(!editingId)setSendNotification(next==="urgent")}
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");setNotice("");try{const response=await fetch("/api/admin/announcements",{method:editingId?"PATCH":"POST",headers:{"Content-Type":"application/json",...authHeaders},body:JSON.stringify({id:editingId,title,message:category==="link"?null:message,link_url:category==="link"?linkUrl:null,sender:notificationSender,category,is_pinned:pinned,send_notification:!editingId&&sendNotification})});const result=await response.json();if(!response.ok)throw new Error(result.error);if(editingId)setNotice("Announcement updated.");else if(!sendNotification)setNotice("Announcement published.");else if(!result.notification?.configured)setNotice("Announcement published, but push notifications are not configured.");else if(result.notification.failed>0&&result.notification.sent===0)setNotice("Announcement published, but notifications could not be sent.");else setNotice(`Announcement published. Notification sent to ${result.notification.sent} device${result.notification.sent===1?"":"s"}.`);reset();await load()}catch(issue){setError(issue instanceof Error?issue.message:"Could not save announcement.")}finally{setSaving(false)}}
  async function updatePin(id:string,is_pinned:boolean){const response=await fetch("/api/admin/announcements",{method:"PATCH",headers:{"Content-Type":"application/json",...authHeaders},body:JSON.stringify({id,is_pinned})});if(!response.ok)setError((await response.json()).error);else await load()}
  async function remove(id:string){if(!confirm("Delete this announcement?"))return;const response=await fetch(`/api/admin/announcements?id=${encodeURIComponent(id)}`,{method:"DELETE",headers:authHeaders});if(!response.ok)setError((await response.json()).error);else{if(editingId===id)reset();await load()}}
  return <main className="min-h-dvh bg-[var(--cream)] p-4 safe-top md:p-8"><div className="mx-auto max-w-3xl">
    <header className="mb-6 flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[var(--dark-cyan)]">YLC organizers</p><h1 className="font-display text-4xl text-[var(--charcoal-blue)]">Announcements</h1></div><button onClick={onLogout} className="grid size-10 place-items-center rounded-full bg-white shadow-sm" aria-label="Log out"><LogOut size={17}/></button></header>
    <form onSubmit={submit} className="card space-y-4 p-5"><div className="flex items-center justify-between"><h2 className="font-display text-2xl text-[var(--charcoal-blue)]">{editingId?"Edit announcement":"New announcement"}</h2>{editingId&&<button type="button" onClick={reset} className="flex items-center gap-1 text-xs font-bold text-[var(--muted)]"><X size={14}/>Cancel</button>}</div>
      <label className="block text-sm font-bold">Category<select value={category} onChange={event=>changeCategory(event.target.value as AnnouncementCategory)} className="mt-2 min-h-11 w-full rounded-xl border bg-white px-3">{categories.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
      <label className="block text-sm font-bold">{category==="link"?"Subject":"Title"}<input value={title} onChange={event=>setTitle(event.target.value)} required className="mt-2 min-h-11 w-full rounded-xl border px-3 outline-none focus:ring-2 focus:ring-[var(--strong-cyan)]"/></label>
      <label className="block text-sm font-bold">From <span className="font-medium text-[var(--muted)]">(optional)</span><input value={notificationSender} onChange={event=>setNotificationSender(event.target.value)} maxLength={80} placeholder="YLC" className="mt-2 min-h-11 w-full rounded-xl border px-3 outline-none focus:ring-2 focus:ring-[var(--strong-cyan)]"/><span className="mt-1 block text-[10px] font-medium text-[var(--muted)]">Shown in the app and notification. Defaults to YLC.</span></label>
      {category==="link"?<label className="block text-sm font-bold">Link<input type="url" inputMode="url" placeholder="https://…" value={linkUrl} onChange={event=>setLinkUrl(event.target.value)} required className="mt-2 min-h-11 w-full rounded-xl border px-3 outline-none focus:ring-2 focus:ring-[var(--strong-cyan)]"/></label>:<label className="block text-sm font-bold">Message<textarea value={message} onChange={event=>setMessage(event.target.value)} required className="mt-2 min-h-28 w-full rounded-xl border p-3 outline-none focus:ring-2 focus:ring-[var(--strong-cyan)]"/></label>}
      <label className="flex items-center justify-between text-sm font-bold">Pin announcement<input type="checkbox" checked={pinned} onChange={event=>setPinned(event.target.checked)} className="size-5 accent-[var(--dark-cyan)]"/></label>
      {!editingId&&<label className="flex items-center justify-between text-sm font-bold"><span>Send phone notification<span className="mt-0.5 block text-[10px] font-medium text-[var(--muted)]">Sends only when this announcement is published.</span></span><input type="checkbox" checked={sendNotification} onChange={event=>setSendNotification(event.target.checked)} className="size-5 accent-[var(--dark-cyan)]"/></label>}
      {error&&<p className="rounded-xl bg-[#f5dfdf] p-3 text-sm font-bold text-[#965555]">{error}</p>}<button disabled={saving} className="min-h-12 w-full rounded-xl bg-[var(--dark-cyan)] font-bold text-white disabled:opacity-50">{saving?"Saving…":editingId?"Save changes":"Publish announcement"}</button>
    </form>
    {notice&&<p className="mt-4 rounded-xl bg-[#dcefe8] p-3 text-sm font-bold text-[#39745e]">{notice}</p>}
    <section className="mt-7"><h2 className="mb-3 font-display text-2xl text-[var(--charcoal-blue)]">Published</h2><div className="space-y-3">{items.map(item=><article key={item.id} className="card p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2 text-[10px] font-black uppercase text-[var(--dark-cyan)]"><span>{item.category}</span><span>From: {item.sender||"YLC"}</span>{item.is_pinned&&<Pin size={12}/>}</div><h3 className="mt-1 font-bold">{item.title}</h3><p className="mt-1 truncate text-sm text-[var(--muted)]">{item.category==="link"?item.link_url:item.message||""}</p></div><div className="flex shrink-0 gap-1"><button onClick={()=>edit(item)} className="grid size-9 place-items-center rounded-xl border" aria-label="Edit"><Pencil size={15}/></button><button onClick={()=>updatePin(item.id,!item.is_pinned)} className="grid size-9 place-items-center rounded-xl border" aria-label={item.is_pinned?"Unpin":"Pin"}>{item.is_pinned?<PinOff size={15}/>:<Pin size={15}/>}</button><button onClick={()=>remove(item.id)} className="grid size-9 place-items-center rounded-xl border text-[#965555]" aria-label="Delete"><Trash2 size={15}/></button></div></div></article>)}{!items.length&&!error&&<p className="card p-6 text-center text-sm text-[var(--muted)]">No announcements yet.</p>}</div></section>
  </div></main>;
}
