"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { usePathname } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { AnnouncementNotificationStatus, enablePush, getAnnouncementNotificationStatus, isIOSBrowser } from "@/lib/push-client";
import { useParticipant } from "./participant-session";
import { Sheet } from "./ui";

const reminderStates:AnnouncementNotificationStatus[]=["permission_default","permission_granted_no_subscription","subscription_not_saved"];
export function PostSigninNotificationPrompt(){const pathname=usePathname();const {signInVersion}=useParticipant();const [status,setStatus]=useState<AnnouncementNotificationStatus|null>(null);const [dismissedVersion,setDismissedVersion]=useState(0);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const check=useCallback(()=>{setStatus(null);void getAnnouncementNotificationStatus().then(setStatus)},[]);useEffect(()=>{if(signInVersion>0)check()},[signInVersion,check]);useEffect(()=>{const changed=()=>{if(signInVersion>0)check()};const visible=()=>{if(signInVersion>0&&document.visibilityState==="visible")check()};window.addEventListener("ylc-push-status-changed",changed);document.addEventListener("visibilitychange",visible);return()=>{window.removeEventListener("ylc-push-status-changed",changed);document.removeEventListener("visibilitychange",visible)}},[signInVersion,check]);const avoidDuplicate=pathname.startsWith("/announcements");const show=signInVersion>0&&dismissedVersion!==signInVersion&&!avoidDuplicate&&status!==null&&reminderStates.includes(status);async function enable(){if(isIOSBrowser()){setDismissedVersion(signInVersion);return}setBusy(true);try{const next=await enablePush();setStatus(next);if(next==="subscribed")setDismissedVersion(signInVersion)}catch(issue){setMessage(issue instanceof Error?issue.message:"Could not enable notifications.")}finally{setBusy(false)}}return <Sheet open={show} onClose={()=>setDismissedVersion(signInVersion)} title={isIOSBrowser()?"Add YLC to your Home Screen":"Stay in the loop"}>{isIOSBrowser()?<><p className="text-sm leading-relaxed text-[var(--muted)]">To enable notifications on iPhone or iPad:</p><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm text-[var(--muted)]"><li>Tap the Share button in Safari.</li><li>Choose Add to Home Screen.</li><li>Open YLC 2026 from the new Home Screen icon.</li><li>Return to Settings and enable notifications.</li></ol><button onClick={()=>setDismissedVersion(signInVersion)} className="mt-5 min-h-11 w-full rounded-xl bg-[var(--dark-cyan)] font-bold text-white">Got it</button></>:<><p className="leading-relaxed text-[var(--muted)]">Turn on announcement notifications so you do not miss schedule changes or important conference updates.</p><div className="mt-5 flex gap-2"><button onClick={enable} disabled={busy} className="min-h-11 flex-1 rounded-xl bg-[var(--dark-cyan)] px-3 text-sm font-bold text-white">{busy?"Enabling…":"Enable notifications"}</button><button onClick={()=>setDismissedVersion(signInVersion)} className="min-h-11 rounded-xl border bg-white px-4 text-sm font-bold">Not now</button></div>{message&&<p className="mt-3 text-xs font-bold text-[#965555]">{message}</p>}</>}</Sheet>}
