"use client";
import { Bell, CheckCircle2, Send } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { AnnouncementNotificationStatus, disablePush, enablePush, getAnnouncementNotificationStatus, isIOSBrowser, sendDeviceTest } from "@/lib/push-client";
import { Sheet } from "./ui";

export function PushNotificationSettings({compact=false}:{compact?:boolean}) {
  const [status,setStatus]=useState<AnnouncementNotificationStatus|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [instructions,setInstructions]=useState(false);
  const check=useCallback(()=>{void getAnnouncementNotificationStatus().then(setStatus)},[]);
  useEffect(()=>{check();const changed=()=>check();const visible=()=>{if(document.visibilityState==="visible")check()};window.addEventListener("ylc-push-status-changed",changed);document.addEventListener("visibilitychange",visible);return()=>{window.removeEventListener("ylc-push-status-changed",changed);document.removeEventListener("visibilitychange",visible)}},[check]);
  async function toggle(){if(isIOSBrowser()&&status!=="subscribed"){setInstructions(true);return}setBusy(true);setMessage("");try{if(status==="subscribed"){await disablePush();setStatus(await getAnnouncementNotificationStatus());setMessage("Announcement notifications are off.")}else{const next=await enablePush();setStatus(next);if(next==="subscribed")setMessage("Announcement notifications are on.");else if(next==="subscription_not_saved")setMessage("Browser notifications are allowed, but this device could not be saved yet.")}}catch(issue){setStatus("error");setMessage(issue instanceof Error?issue.message:"Could not update notifications.")}finally{setBusy(false)}}
  async function test(){setBusy(true);setMessage("");try{await sendDeviceTest();setMessage("Test sent to this device.")}catch(issue){setMessage(issue instanceof Error?issue.message:"Could not send the test.")}finally{setBusy(false)}}
  const enabled=status==="subscribed";const denied=status==="permission_denied";const unsupported=status==="unsupported";
  return <><section className={`card ${compact?"p-4":"p-4"}`}><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#dff5f3] text-[var(--dark-cyan)]">{enabled?<CheckCircle2 size={19}/>:<Bell size={19}/>}</span><div className="min-w-0 flex-1"><h2 className="font-bold">Announcement notifications</h2><p className="mt-1 text-xs text-[var(--muted)]">Get notified when organizers post an important announcement.</p>{status&&<p className="mt-2 text-xs font-black text-[var(--dark-cyan)]">{enabled?"Announcement notifications are on.":denied?"Notifications are disabled.":unsupported?"Not supported on this device.":isIOSBrowser()?"Add to Home Screen to enable.":status==="error"?"Could not check notification status.":"Notifications are off."}</p>}{process.env.NODE_ENV==="development"&&<p className="mt-1 font-mono text-[9px] text-[var(--muted)]">Detected: {status||"checking"}</p>}</div></div>{denied?<p className="mt-3 rounded-xl bg-[#fff0c8] p-3 text-xs font-bold text-[var(--muted)]">Re-enable notifications through your device or browser settings, then return here.</p>:!unsupported&&status&&<div className="mt-4 flex gap-2"><button onClick={toggle} disabled={busy} className="min-h-11 flex-1 rounded-xl bg-[var(--dark-cyan)] px-3 text-sm font-bold text-white disabled:opacity-55">{busy?"Working…":enabled?"Turn off notifications":"Enable announcement notifications"}</button>{enabled&&<button onClick={test} disabled={busy} aria-label="Send test notification" className="grid size-11 place-items-center rounded-xl border bg-white"><Send size={16}/></button>}</div>}{message&&<p className="mt-3 rounded-xl bg-[#fff0c8] p-3 text-xs font-bold text-[var(--muted)]">{message}</p>}</section><Sheet open={instructions} onClose={()=>setInstructions(false)} title="Add to Home Screen"><ol className="list-decimal space-y-3 pl-5 text-sm leading-relaxed text-[var(--muted)]"><li>Tap the Share button in Safari.</li><li>Choose <b>Add to Home Screen</b>.</li><li>Open YLC 2026 from the new Home Screen icon.</li><li>Return here and tap Enable announcement notifications.</li></ol></Sheet></>;
}
