"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { Bell, CheckCircle2 } from "lucide-react";
import { useEffect, useState } from "react";

function supported() { return "Notification" in window && "serviceWorker" in navigator && "PushManager" in window; }
function installed() { return matchMedia("(display-mode: standalone)").matches || Boolean((navigator as Navigator & { standalone?: boolean }).standalone); }
function isIOS() { return /iPad|iPhone|iPod/.test(navigator.userAgent); }
function applicationKey(value:string){const padding="=".repeat((4-value.length%4)%4);return Uint8Array.from(atob((value+padding).replace(/-/g,"+").replace(/_/g,"/")),char=>char.charCodeAt(0))}

export function PushNotificationSettings() {
  const [status,setStatus]=useState("Not enabled"); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  useEffect(()=>{if(!supported())setStatus("Unsupported on this device");else if(isIOS()&&!installed())setStatus("Add to Home Screen first");else if(Notification.permission==="granted")setStatus("Enabled");else if(Notification.permission==="denied")setStatus("Permission denied")},[]);
  async function enable(){setBusy(true);setMessage("");try{if(!supported())throw new Error("Notifications are not supported on this device.");if(isIOS()&&!installed())throw new Error("On iPhone or iPad, add YLC 2026 to your Home Screen, then open it from the icon and try again.");const permission=await Notification.requestPermission();if(permission!=="granted"){setStatus(permission==="denied"?"Permission denied":"Not enabled");return}const publicKey=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;if(!publicKey)throw new Error("Push notifications still need the public VAPID key.");const registration=await navigator.serviceWorker.ready;const subscription=(await registration.pushManager.getSubscription())||(await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:applicationKey(publicKey)}));const response=await fetch("/api/push/subscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(subscription.toJSON())});const result=await response.json();if(!response.ok)throw new Error(result.error);setStatus("Enabled");setMessage("You’ll receive new YLC announcements on this device.")}catch(issue){setStatus("Not enabled");setMessage(issue instanceof Error?issue.message:"Could not enable notifications.")}finally{setBusy(false)}}
  return <section className="card p-4"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#dff5f3] text-[var(--dark-cyan)]">{status==="Enabled"?<CheckCircle2 size={19}/>:<Bell size={19}/>}</span><div className="min-w-0 flex-1"><h2 className="font-bold">Announcement notifications</h2><p className="mt-1 text-xs text-[var(--muted)]">Get a phone alert when organizers post an announcement.</p><p className="mt-2 text-xs font-black text-[var(--dark-cyan)]">{status}</p></div></div><button onClick={enable} disabled={busy||status==="Enabled"} className="mt-4 min-h-11 w-full rounded-xl bg-[var(--dark-cyan)] px-3 text-sm font-bold text-white disabled:opacity-55">{busy?"Enabling…":status==="Enabled"?"Notifications enabled":"Enable notifications"}</button>{message&&<p className="mt-3 rounded-xl bg-[#fff0c8] p-3 text-xs font-bold text-[var(--muted)]">{message}</p>}</section>;
}
