"use client";
import { Bell, CheckCircle2, Send } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { currentPushStatus, disablePush, enablePush, PushStatus, sendDeviceTest } from "@/lib/push-client";
import { Sheet } from "./ui";

export function PushNotificationSettings({compact=false}:{compact?:boolean}) {
  const [status,setStatus]=useState<PushStatus>("checking");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [instructions,setInstructions]=useState(false);
  const check=useCallback(()=>{void currentPushStatus().then(setStatus).catch(()=>setStatus("failed"))},[]);
  useEffect(()=>{check();window.addEventListener("ylc-push-status-changed",check);return()=>window.removeEventListener("ylc-push-status-changed",check)},[check]);
  async function toggle(){if(status==="ios-browser"){setInstructions(true);return}setBusy(true);setMessage("");try{if(status==="enabled"){await disablePush();setStatus("not-subscribed");setMessage("Announcement notifications are off.")}else setStatus(await enablePush())}catch(issue){setStatus("failed");setMessage(issue instanceof Error?issue.message:"Could not update notifications.")}finally{setBusy(false)}}
  async function test(){setBusy(true);setMessage("");try{await sendDeviceTest();setMessage("Test sent to this device.")}catch(issue){setMessage(issue instanceof Error?issue.message:"Could not send the test.")}finally{setBusy(false)}}
  const denied=status==="denied";const enabled=status==="enabled";
  return <><section className={`card ${compact?"p-4":"p-4"}`}><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#dff5f3] text-[var(--dark-cyan)]">{enabled?<CheckCircle2 size={19}/>:<Bell size={19}/>}</span><div className="min-w-0 flex-1"><h2 className="font-bold">Announcement notifications</h2><p className="mt-1 text-xs text-[var(--muted)]">Get notified when organizers post an important announcement.</p><p className="mt-2 text-xs font-black text-[var(--dark-cyan)]">{enabled?"Announcement notifications are on.":denied?"Notifications are disabled.":status==="unsupported"?"Not supported on this device.":status==="ios-browser"?"Add to Home Screen to enable.":"Notifications are off."}</p></div></div>{denied?<p className="mt-3 rounded-xl bg-[#fff0c8] p-3 text-xs font-bold text-[var(--muted)]">Re-enable notifications through your device or browser settings, then return here.</p>:status!=="unsupported"&&<div className="mt-4 flex gap-2"><button onClick={toggle} disabled={busy||status==="checking"} className="min-h-11 flex-1 rounded-xl bg-[var(--dark-cyan)] px-3 text-sm font-bold text-white disabled:opacity-55">{busy?"Working…":enabled?"Turn off notifications":"Enable announcement notifications"}</button>{enabled&&<button onClick={test} disabled={busy} aria-label="Send test notification" className="grid size-11 place-items-center rounded-xl border bg-white"><Send size={16}/></button>}</div>}{message&&<p className="mt-3 rounded-xl bg-[#fff0c8] p-3 text-xs font-bold text-[var(--muted)]">{message}</p>}</section><Sheet open={instructions} onClose={()=>setInstructions(false)} title="Add to Home Screen"><ol className="list-decimal space-y-3 pl-5 text-sm leading-relaxed text-[var(--muted)]"><li>Tap the Share button in Safari.</li><li>Choose <b>Add to Home Screen</b>.</li><li>Open YLC 2026 from the new Home Screen icon.</li><li>Return to Settings and tap Enable announcement notifications.</li></ol></Sheet></>;
}
