"use client";
import { AnimatePresence, motion } from "framer-motion";
import { Check, ChevronRight, X } from "lucide-react";
import { ReactNode } from "react";

export function Button({children,variant="primary",className="",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"ghost"}){
 const styles={primary:"bg-[var(--dark-cyan)] text-white shadow-lg shadow-[#294956]/15 hover:bg-[var(--charcoal-blue)]",secondary:"bg-white text-[var(--dark-cyan)] border border-[var(--line)] hover:bg-[var(--strong-cyan)]/10",ghost:"text-[var(--dark-cyan)] hover:bg-[var(--strong-cyan)]/10"};
 return <button className={`min-h-12 rounded-2xl px-5 font-bold transition active:scale-[.97] ${styles[variant]} ${className}`} {...props}>{children}</button>
}
export function Field({label,hint,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;hint?:string}){
 return <label className="block"><span className="mb-2 block text-sm font-bold text-[var(--forest)]">{label}</span><input className="min-h-13 w-full rounded-2xl border border-green-900/15 bg-white px-4 outline-none transition placeholder:text-stone-400 focus:border-[var(--green)] focus:ring-4 focus:ring-green-700/10" {...props}/>{hint&&<span className="mt-1.5 block text-xs text-[var(--muted)]">{hint}</span>}</label>
}
export function PageHeader({eyebrow,title,action}: {eyebrow?:string;title:string;action?:ReactNode}) { return <header className="mb-6 flex items-end justify-between gap-4"><div>{eyebrow&&<p className="mb-1 text-xs font-extrabold uppercase tracking-[.18em] text-[var(--dark-cyan)]">{eyebrow}</p>}<h1 className="font-display text-4xl leading-tight text-[var(--charcoal-blue)] md:text-5xl">{title}</h1></div>{action}</header> }
export function Pill({children,color="#e7eee9"}:{children:ReactNode;color?:string}) { return <span className="inline-flex items-center rounded-full px-3 py-1 text-xs font-extrabold" style={{background:color}}>{children}</span> }
export function Progress({value,color="var(--green)"}:{value:number;color?:string}) { return <div className="h-2.5 overflow-hidden rounded-full bg-black/8"><motion.div initial={{width:0}} animate={{width:`${value}%`}} transition={{duration:.8,ease:"easeOut"}} className="h-full rounded-full" style={{background:color}} /></div> }
export function Sheet({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}) { return <AnimatePresence>{open&&<><motion.button aria-label="Close modal" onClick={onClose} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-[#102a22]/50 backdrop-blur-sm"/><motion.section role="dialog" aria-modal="true" aria-label={title} initial={{y:"100%"}} animate={{y:0}} exit={{y:"100%"}} transition={{type:"spring",damping:28,stiffness:260}} className="fixed inset-x-0 bottom-0 z-50 mx-auto max-h-[88dvh] max-w-2xl overflow-y-auto rounded-t-[30px] bg-[var(--paper)] p-5 pb-10 shadow-2xl md:bottom-6 md:rounded-[30px]"><div className="mx-auto mb-4 h-1.5 w-12 rounded-full bg-green-900/15"/><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-2xl font-bold text-[var(--forest)]">{title}</h2><button onClick={onClose} aria-label="Close" className="rounded-full bg-green-900/5 p-2"><X size={20}/></button></div>{children}</motion.section></>}</AnimatePresence> }
export function EmptyState({title,body}:{title:string;body:string}) { return <div className="card p-8 text-center"><div className="mx-auto mb-4 grid size-12 place-items-center rounded-full bg-green-100"><Check className="text-green-700"/></div><h3 className="font-display text-xl font-bold">{title}</h3><p className="mt-2 text-sm text-[var(--muted)]">{body}</p></div> }
export function LinkRow({icon,title,subtitle,onClick}:{icon:ReactNode;title:string;subtitle?:string;onClick?:()=>void}) { return <button onClick={onClick} className="flex w-full items-center gap-3 border-b border-green-900/8 px-1 py-4 text-left last:border-0"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-green-900/6 text-[var(--green)]">{icon}</span><span className="min-w-0 flex-1"><span className="block font-bold">{title}</span>{subtitle&&<span className="block truncate text-sm text-[var(--muted)]">{subtitle}</span>}</span><ChevronRight size={18} className="text-stone-400"/></button> }
