"use client";
export type PushStatus="checking"|"unsupported"|"ios-browser"|"not-requested"|"denied"|"not-subscribed"|"enabled"|"failed";
export function pushSupported(){return "Notification" in window&&"serviceWorker" in navigator&&"PushManager" in window}
export function isIOSBrowser(){const ios=/iPad|iPhone|iPod/.test(navigator.userAgent);const standalone=matchMedia("(display-mode: standalone)").matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone);return ios&&!standalone}
function applicationKey(value:string){const padding="=".repeat((4-value.length%4)%4);return Uint8Array.from(atob((value+padding).replace(/-/g,"+").replace(/_/g,"/")),char=>char.charCodeAt(0))}
export async function currentPushStatus():Promise<PushStatus>{if(!pushSupported())return "unsupported";if(isIOSBrowser())return "ios-browser";if(Notification.permission==="denied")return "denied";if(Notification.permission!=="granted")return "not-requested";const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.getSubscription();if(!subscription)return "not-subscribed";const response=await fetch(`/api/push/subscribe?endpoint=${encodeURIComponent(subscription.endpoint)}`,{cache:"no-store"});if(!response.ok)return "not-subscribed";return (await response.json()).active?"enabled":"not-subscribed"}
export async function enablePush(){if(!pushSupported())throw new Error("Notifications are not supported on this device.");if(isIOSBrowser())throw new Error("Add YLC 2026 to your Home Screen first.");const permission=await Notification.requestPermission();if(permission!=="granted")return permission==="denied"?"denied" as const:"not-requested" as const;const publicKey=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;if(!publicKey)throw new Error("The public VAPID key is missing.");const registration=await navigator.serviceWorker.ready;const subscription=(await registration.pushManager.getSubscription())||(await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:applicationKey(publicKey)}));const response=await fetch("/api/push/subscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(subscription.toJSON())});const result=await response.json();if(!response.ok)throw new Error(result.error);window.dispatchEvent(new Event("ylc-push-status-changed"));return "enabled" as const}
export async function disablePush(){if(!pushSupported())return;const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.getSubscription();if(subscription){const response=await fetch("/api/push/unsubscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({endpoint:subscription.endpoint})});if(!response.ok)throw new Error((await response.json()).error);await subscription.unsubscribe()}window.dispatchEvent(new Event("ylc-push-status-changed"))}
export async function sendDeviceTest(){const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.getSubscription();if(!subscription)throw new Error("Enable notifications first.");const response=await fetch("/api/push/test",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({endpoint:subscription.endpoint})});const result=await response.json();if(!response.ok)throw new Error(result.error)}
