"use client";
import { CalendarDays, Clock3 } from "lucide-react";
import { useMemo, useState } from "react";
import { PageHeader } from "@/components/ui";

const days=[
 {date:"2026-08-05",short:"Wed, Aug 5",label:"Day 1",events:[["10:00 AM","Introduction"],["10:15 AM","Meet Your Team"],["11:00 AM","Keynote: Camille Chu"],["11:15 AM","Keynote: Dr. Samuel So"],["12:00 PM","Lunch"],["1:00 PM","Keynote: Sa Nguyen"],["2:00 PM","Team Activity"],["2:30 PM","Break"],["3:00 PM","Team Challenge Introduction"],["3:15 PM","Working Session"],["4:00 PM","Keynote: Miyu & Timothy"],["5:00 PM","Closing"]]},
 {date:"2026-08-06",short:"Thurs, Aug 6",label:"Day 2",events:[["10:00 AM","Introduction"],["10:15 AM","Team Activity"],["11:00 AM","Working Session"],["12:30 PM","Lunch"],["1:30 PM","Keynote: Judy Huynh"],["2:30 PM","Break"],["3:00 PM","Keynote: Austin Pliler"],["4:00 PM","Team HBV Presentation"],["4:30 PM","Working Session"],["5:00 PM","Closing"]]},
 {date:"2026-08-07",short:"Fri, Aug 7",label:"Day 3",events:[["10:00 AM","Introduction"],["10:15 AM","Keynote: Dr. Crystal Hlaing Reece"],["11:15 AM","Team Activity"],["12:00 PM","Lunch"],["1:00 PM","Keynote: Koy Suntichotinun"],["2:00 PM","Break"],["2:30 PM","Student Panel"],["3:30 PM","Working Session"],["5:00 PM","Closing"]]},
 {date:"2026-08-08",short:"Sat, Aug 8",label:"Day 4",events:[["10:00 AM","Introduction"],["10:30 AM","Final Working Session"],["11:30 AM","Lunch"],["12:30 PM","Team Presentations"],["1:20 PM","Break"],["1:30 PM","Team Presentations"],["2:20 PM","Judges’ Deliberation"],["2:30 PM","Announcement of Winners and Closing Remarks"],["3:00 PM","The End"]]},
] as const;

export default function Schedule(){const today=useMemo(()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Los_Angeles",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),[]);const todayIndex=days.findIndex(day=>day.date===today);const [selected,setSelected]=useState(todayIndex>=0?todayIndex:0);const day=days[selected];return <div className="mx-auto max-w-3xl"><PageHeader eyebrow="All times Pacific Daylight Time" title="Schedule" action={<span className="grid size-12 place-items-center rounded-2xl bg-[#fff0c8] text-[#a56a21]"><CalendarDays/></span>}/><div className="no-scrollbar -mx-4 mb-6 flex gap-2 overflow-x-auto px-4 pb-2">{days.map((item,index)=><button key={item.date} onClick={()=>setSelected(index)} className={`min-w-28 rounded-2xl border px-4 py-3 text-left transition ${selected===index?"border-[var(--charcoal-blue)] bg-[var(--charcoal-blue)] text-white shadow-lg":"border-[var(--line)] bg-white"}`}><span className="block text-xs font-black">{item.label}{item.date===today?" · Today":""}</span><span className="mt-1 block text-[11px] opacity-70">{item.short}</span></button>)}</div><section><div className="mb-3 flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-[var(--dark-cyan)]">{day.label}</p><h2 className="font-display text-3xl text-[var(--charcoal-blue)]">{day.short}</h2></div>{day.date===today&&<span className="rounded-full bg-[#fff0c8] px-3 py-1 text-xs font-black text-[#8d5e1d]">Today</span>}</div><div className="space-y-2">{day.events.map(([time,title],index)=><div key={`${time}-${title}`} className={`flex items-center gap-3 rounded-2xl border border-[var(--line)] bg-white p-3 shadow-sm ${title.includes("Team")||title.includes("Working")?"border-l-4 border-l-[var(--strong-cyan)]":""}`}><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[var(--charcoal-blue)]/5 text-[var(--dark-cyan)]"><Clock3 size={17}/></span><time className="w-18 shrink-0 text-xs font-extrabold text-[var(--charcoal-blue)]">{time}</time><div className="h-8 w-px bg-[var(--line)]"/><p className="min-w-0 flex-1 text-sm font-bold leading-snug">{title}</p><span className="text-[10px] font-black text-stone-300">{String(index+1).padStart(2,"0")}</span></div>)}</div></section></div>}
