import { createClient } from "npm:@supabase/supabase-js@2";
import webpush from "npm:web-push@3.6.7";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
 const url=Deno.env.get("SUPABASE_URL")!;const secret=Deno.env.get("SUPABASE_SECRET_KEY")!;
 const auth=req.headers.get("Authorization")||"";const admin=createClient(url,secret,{auth:{persistSession:false}});
 const token=auth.replace("Bearer ","");const {data:{user},error:userError}=await admin.auth.getUser(token);
 if(userError||!user||user.app_metadata?.role!=="admin")return Response.json({error:"Unauthorized"},{status:401,headers:cors});
 const {announcementId,testOnly=false}=await req.json();const {data:announcement,error}=await admin.from("announcements").select("*").eq("id",announcementId).eq("status","published").single();if(error||!announcement)return Response.json({error:"Published announcement not found"},{status:404,headers:cors});
 let participantIds:string[]|null=null;if(testOnly)participantIds=[user.id];else if(announcement.audience_type!=="everyone"){let query=admin.from("participant_profiles").select("user_id");if(announcement.audience_type==="team")query=query.eq("team_id",announcement.audience_team_id);else query=query.in("role",["admin","organizer"]);const {data}=await query;participantIds=(data||[]).map((row:{user_id:string})=>row.user_id)}
 let query=admin.from("notification_subscriptions").select("id,participant_id,endpoint,p256dh,auth,notification_preferences!inner(urgent_announcements_enabled)").eq("active",true).eq("notification_preferences.urgent_announcements_enabled",true);if(participantIds)query=query.in("participant_id",participantIds);const {data:subscriptions,error:subError}=await query;if(subError)throw subError;
 webpush.setVapidDetails(Deno.env.get("VAPID_SUBJECT")!,Deno.env.get("VAPID_PUBLIC_KEY")!,Deno.env.get("VAPID_PRIVATE_KEY")!);let sent=0,failed=0,skipped=0;
 for(const sub of subscriptions||[]){const dedup=`announcement:${announcement.id}:subscription:${sub.id}`;const {error:claimError}=await admin.from("announcement_push_deliveries").insert({announcement_id:announcement.id,push_subscription_id:sub.id,participant_id:sub.participant_id,status:"attempting",deduplication_key:dedup});if(claimError){skipped++;continue}try{await webpush.sendNotification({endpoint:sub.endpoint,keys:{p256dh:sub.p256dh,auth:sub.auth}},JSON.stringify({title:announcement.title,body:announcement.message.slice(0,160),announcementId:announcement.id,category:announcement.category,priority:announcement.priority,actionUrl:announcement.action_url}),{TTL:86400});sent++;await admin.from("announcement_push_deliveries").update({status:"delivered",delivered_at:new Date().toISOString()}).eq("deduplication_key",dedup);await admin.from("notification_subscriptions").update({last_used_at:new Date().toISOString()}).eq("id",sub.id)}catch(e:unknown){failed++;const pushError=e as {statusCode?:number;message?:string};const expired=[404,410].includes(pushError.statusCode||0);await admin.from("announcement_push_deliveries").update({status:"failed",error_message:String(pushError.message||e)}).eq("deduplication_key",dedup);if(expired)await admin.from("notification_subscriptions").update({active:false}).eq("id",sub.id)}}return Response.json({sent,failed,skipped},{headers:{...cors,"Content-Type":"application/json"}})
 }catch(error){return Response.json({error:error instanceof Error?error.message:"Unknown error"},{status:500,headers:cors})}});
